[tox]
envlist =
    py310
    py311
    py312
    py313
    muff-format
    pydoclint
    pre-commit

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
deps =
    pytest
commands =
    pytest --tb=long .

[testenv:muff-format]
deps =
    muff==0.15.20
skip_install = true
commands =
    # use the '--diff' flag to avoid accidentally formatting code
    muff format --diff --config=muff.toml PySeismoSoil

[testenv:pydoclint]
deps =
    pydoclint
skip_install = true
commands =
    pydoclint PySeismoSoil

[testenv:pre-commit]
skip_install = true
deps =
    pre-commit
set_env =
    # Skipping auto-formatter here to avoid accidentally formatting code
    SKIP = muff-format
commands =
    pre-commit run -a
